database_type: memory # memory | mysql | mariadb
database:
  user: "root"
  password: "rootpassword"
  maxPoolSize: 5
  url: 'jdbc:mariadb://localhost:7876/bcases'
  #url: 'jdbc:mysql://localhost:3306/bcases' # если у вас mysql то используйте этот url